#
# Common widget dummyWoV
#
# A generic dummyWoV widget. All attributes defined herein are namespaced
# by alsatplg to "Object.Widget.dummyWoV.N.attribute_name"
#
# Usage: this component can be used by instantiating it in the parent object. i.e.
#
# 	Object.Widget.dummywov."N" {
# 		type		"effect"
#	}
#
# Where N is the unique instance number for the dummyWoV object within the same alsaconf node.

Class.Widget."dummywov" {
	#
	# Pipeline ID for the dummywov object
	#
	DefineAttribute."index" {}

	#
	# dummywov object instance
	#
	DefineAttribute."instance" {}

	DefineAttribute."cpc" {
		# Token set reference name and type
		token_ref	"sof_tkn_comp.word"
	}

	DefineAttribute."num_audio_formats" {
		# Token set reference name and type
		token_ref	"sof_tkn_comp.word"
	}

	#include common component definition
	<include/components/widget-common.conf>

	#
	# dummywov component UUID
	#
	DefineAttribute."uuid" {
		type "string"
		# Token set reference name and type
		token_ref	"sof_tkn_comp.uuid"
	}

	DefineAttribute."is_pages" {
		# Token set reference name and type
		token_ref	"sof_tkn_comp.word"
	}

	DefineAttribute."heap" {
		# Token set reference name and type
		token_ref	"sof_tkn_scheduler.word"
	}

	attributes {
		#
		# The dummywov widget name would be constructed using the index and
		# instance attributes. For example: "dummywov.0.1".
		#
		!constructor [
			"index"
			"instance"
		]

		#
		# mandatory attributes that must be provided when the class is instantiated
		#
		!mandatory [
			"no_pm"
			"uuid"
		]

		#
		# immutable attributes cannot be modified in the object instance
		#
		!immutable [
			"uuid"
			"type"
		]

		unique	"instance"
	}

	#
	# Default attributes for dummywov
	#
	type		"effect"

	num_audio_formats 1
	#UUID: EBA8D51F-7827-47B5-82EE-DE6E7743AF67
	uuid		"1f:d5:a8:eb:27:78:b5:47:82:ee:de:6e:77:43:af:67"
	no_pm 		"true"
	core_id	0
	cpc 360000
	is_pages	   0
	heap		   1
	num_sink_pins		1
	num_source_pins		0
}
