#
# NONE DAI class definition. All attributes defined herein are namespaced
# by alsatplg to "Object.Dai.NONE.N.attribute_name"
#
# Usage: NONE DAI is a dummy object that can be instantiated as:
#
# Object.Dai.NONE."N" {
# 	direction		"capture"
# 	name			"NoCodec-0"
# 	id 			2
# }
#
# where N is the unique instance number for the NONE object within the same alsaconf node.

# NONE port definition
Class.Dai."NONE" {

	#
	# Argument used to construct DAI widget
	#
	# Playback DAI Index
	DefineAttribute."dai_index" {
		token_ref	"sof_tkn_dai.word"
	}

	DefineAttribute."direction" {
		type "string"
		token_ref	"sof_tkn_dai.word"
		constraints {
			!valid_values [
				"playback"
				"capture"
				"duplex"
			]
		}
	}

	DefineAttribute."dai_type" {
		type	"string"
		token_ref	"sof_tkn_dai.string"
	}

	DefineAttribute."default_hw_config_id" {}

	DefineAttribute."name" {
		type	"string"
	}

	DefineAttribute."type" {
		token_ref	"sof_dai_tokens.string"
	}

	DefineAttribute."rate" {
		token_ref	"sof_tkn_alh.word"
	}

	DefineAttribute."channels" {
		token_ref	"sof_tkn_alh.word"
	}

	# Backend DAI Link ID matching with the machine driver
	DefineAttribute."id" {}
	DefineAttribute."default_hw_config_id" {}
	DefineAttribute."dai_name" {}


	attributes {
		!constructor [
			"name"
		]

		!mandatory [
			"format"
		]

		!immutable [
			"dai_type"
		]
		unique	"dai_index"
	}

	dai_type		"NONE"
}
