#
# CAVS passthrough capture pipeline
#
# A simple passthrough pipeline. All attributes defined herein are namespaced
# by alsatplg to "Object.Pipeline.passthrough-capture.N.attribute_name".
#
# Usage: passthrough-capture pipeline object can be instantiated as:
#
# Object.Pipeline.passthrough-capture."N" {
# 	format		"s16le"
# 	period		1000
# 	time_domain	"timer"
# 	channels	2
# 	rate		48000
# }
#
# Where N is the unique pipeline ID within the same alsaconf node.
#

<include/common/audio_format.conf>
<include/components/copier.conf>
<include/components/micsel.conf>
<include/components/dummywov.conf>
<include/components/pipeline.conf>
<include/controls/bytes.conf>
<cavs/common_definitions.conf>

Class.Pipeline."passthrough-wov" {

	DefineAttribute."index" {}

	<include/pipelines/pipeline-common.conf>

	attributes {
		!constructor [
			"index"
		]

		!mandatory [
			"format"
		]

		!immutable [
			"direction"
		]

		#
		# passthrough-capture objects instantiated within the same alsaconf node must have
		# unique pipeline_id attribute
		#
		unique	"instance"
	}

	Object.Widget {

		virtual."virtual.detect_sink" {
			type out_drv
		}

		micsel."1" {
			Object.Base.audio_format.1 {
				in_rate		16000
				out_rate	16000
				in_channels	4
				out_channels	1
				in_ch_map	0xffff3120
				in_ch_cfg	6
				out_ch_map	0xfffffff1
				out_ch_cfg	0
				out_bit_depth	16
				in_bit_depth	16
				in_valid_bit_depth	16
				out_valid_bit_depth	16
			}
		}

		dummywov."1" {
			Object.Base.audio_format.1 {
				in_rate		16000
				out_rate	16000
				in_channels	1
				out_channels	1
				in_ch_cfg	0
				in_ch_map	0xfffffff1
				out_bit_depth	16
				in_bit_depth	16
				in_valid_bit_depth	16
				out_valid_bit_depth	16
				ibs			0x280
				obs			0x280
			}
			Object.Control.bytes."1" {
				name wov_init
				access  [
					tlv_read
					tlv_callback
				]
				Object.Base.extops."extctl" {
					get 258
					put 0
				}
				max 4096
				Object.Base.data."InitPayload" {bytes "0x53, 0x4f, 0x46, 0x34, 0x04, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x04, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x34, 0x21, 0x00, 0x00"}
			}
		}

		pipeline."1" {
			priority	0
			lp_mode		0
			priority	6
		}
	}

	Object.Base {
		route."1" {
			source "micsel..1"
			sink "dummywov..1"
		}

		route."2" {
			source "dummywov..1"
			sink "virtual.detect_sink"
		}
	}

	direction	"capture"
	dynamic_pipeline 1
	time_domain	"timer"
	channels	4
	channels_min	4
	channels_max	4
	rate		16000
	rate_min	16000
	rate_max	16000
}
